/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;

import oru.inf.InfDB;

/**
 *
 * @author filippabostrom
 */
public class ChangeCustomerInfo extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form ChangeCustomerInfo
     */
    public ChangeCustomerInfo(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChangeCustomerInfo = new javax.swing.JLabel();
        cmbChooseCustomer = new javax.swing.JComboBox<>();
        lblChooseCustomer = new javax.swing.JLabel();
        lblCurrentAddress = new javax.swing.JLabel();
        lblShowCurrentEmail = new javax.swing.JLabel();
        lblNewAddress = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        txtNewStreet = new javax.swing.JTextField();
        lblNewHouse_number = new javax.swing.JLabel();
        lblCurrentEmail = new javax.swing.JLabel();
        lblShowCurrentAddress = new javax.swing.JLabel();
        lblNewEmail = new javax.swing.JLabel();
        txtNewHouseNumber = new javax.swing.JTextField();
        lblCurrentName = new javax.swing.JLabel();
        lblShowCurrentName = new javax.swing.JLabel();
        lblNewName = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        btnChangeAddress = new javax.swing.JButton();
        btnChangeName = new javax.swing.JButton();
        btnChangeEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChangeCustomerInfo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblChangeCustomerInfo.setText("Ändra kunduppgifter!");

        lblChooseCustomer.setText("Välj kund");

        lblCurrentAddress.setText("Nuvarande adress:");

        lblShowCurrentEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblNewAddress.setText("Ny gata:");

        txtNewEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });

        txtNewStreet.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblNewHouse_number.setText("Nytt husnummer:");

        lblCurrentEmail.setText("Nuvarande E-post:");

        lblShowCurrentAddress.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblNewEmail.setText("Ny E-post:");

        txtNewHouseNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblCurrentName.setText("Nuvarande namn:");

        lblShowCurrentName.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblNewName.setText("Nytt Namn:");

        txtNewName.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        btnChangeAddress.setText("Ändra adress");

        btnChangeName.setText("Ändra namn");

        btnChangeEmail.setText("Ändra E-post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChangeCustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChooseCustomer)
                            .addComponent(cmbChooseCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurrentEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblShowCurrentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNewEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(btnChangeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCurrentAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblShowCurrentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblNewAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNewStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblNewHouse_number)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNewHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCurrentName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblShowCurrentName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(lblNewName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNewName)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChangeAddress))))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblChangeCustomerInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChooseCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChooseCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShowCurrentName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewName)
                        .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChangeName)
                        .addComponent(lblCurrentName)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowCurrentAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewAddress)
                        .addComponent(txtNewStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCurrentAddress)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewHouse_number)
                    .addComponent(btnChangeAddress))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewEmail)
                        .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChangeEmail))
                    .addComponent(lblCurrentEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblShowCurrentEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeAddress;
    private javax.swing.JButton btnChangeEmail;
    private javax.swing.JButton btnChangeName;
    private javax.swing.JComboBox<String> cmbChooseCustomer;
    private javax.swing.JLabel lblChangeCustomerInfo;
    private javax.swing.JLabel lblChooseCustomer;
    private javax.swing.JLabel lblCurrentAddress;
    private javax.swing.JLabel lblCurrentEmail;
    private javax.swing.JLabel lblCurrentName;
    private javax.swing.JLabel lblNewAddress;
    private javax.swing.JLabel lblNewEmail;
    private javax.swing.JLabel lblNewHouse_number;
    private javax.swing.JLabel lblNewName;
    private javax.swing.JLabel lblShowCurrentAddress;
    private javax.swing.JLabel lblShowCurrentEmail;
    private javax.swing.JLabel lblShowCurrentName;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewHouseNumber;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewStreet;
    // End of variables declaration//GEN-END:variables
}
