/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;

import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import oru.inf.InfDB;
import oru.inf.InfException;



/**
 *
 * @author filippabostrom
 */
public class ChooseCustomerAndOrder extends javax.swing.JFrame {
    private static InfDB idb;
    private int customerID;
    private String customerName;
    
    /**
     * Creates new form ChooseCustomerAndOrder
     */
    public ChooseCustomerAndOrder(InfDB idb) {
        initComponents();
        this.idb = idb;
        fillComboBoxWithCustomers();
        
    }
    
    
    
    private void fillComboBoxWithCustomers() {
        String query = "SELECT name from Customer";
        
        ArrayList <String> allCustomers;
        
        try {
            allCustomers = idb.fetchColumn(query);
            
            for(String namn:allCustomers) {
                cbmCustomers.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    
    private void fillComboBoxWithOrder() {
       String query = "SELECT OrderID from `Order` where Customer = " + customerID + "";
        
        ArrayList <String> allOrderID;
        
        try {
            allOrderID = idb.fetchColumn(query);
            
            for(String order:allOrderID) {
                cbmOrders.addItem(order);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseCustomer = new javax.swing.JLabel();
        cbmCustomers = new javax.swing.JComboBox<>();
        cbmOrders = new javax.swing.JComboBox<>();
        lblChooseOrder = new javax.swing.JLabel();
        btnShowOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChooseCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblChooseCustomer.setText("Välja kund");

        cbmCustomers.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cbmCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCustomersActionPerformed(evt);
            }
        });

        cbmOrders.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cbmOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmOrdersActionPerformed(evt);
            }
        });

        lblChooseOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblChooseOrder.setText("Välj order att ändra ");

        btnShowOrder.setText("Visa ordrar");
        btnShowOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblChooseCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbmOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnShowOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblChooseOrder)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblChooseCustomer)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblChooseOrder)
                .addGap(26, 26, 26)
                .addComponent(cbmOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbmCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCustomersActionPerformed
        
        String ChoosenCustomer = cbmCustomers.getSelectedItem().toString();
        ChoosenCustomer = customerName;
        
        try{
           
            String IDquery = "Select CustomerID from Customer where name = '" + ChoosenCustomer + "'";
            String ID = idb.fetchSingle(IDquery);
            int IDint  = parseInt(ID);
            
            IDint = customerID;
            
        }catch(InfException e){
            
              JOptionPane.showMessageDialog(null, "Något gick fel");
        
    }
            
            
        
        
        
    }//GEN-LAST:event_cbmCustomersActionPerformed

    private void cbmOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmOrdersActionPerformed
       
     
        
        
    
   
    }//GEN-LAST:event_cbmOrdersActionPerformed

    private void btnShowOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowOrderActionPerformed
       
        fillComboBoxWithOrder();
       
    }//GEN-LAST:event_btnShowOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCustomerAndOrder(idb).setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowOrder;
    private javax.swing.JComboBox<String> cbmCustomers;
    private javax.swing.JComboBox<String> cbmOrders;
    private javax.swing.JLabel lblChooseCustomer;
    private javax.swing.JLabel lblChooseOrder;
    // End of variables declaration//GEN-END:variables
}
