/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author theosohlman
 */
public class LoginPage extends javax.swing.JFrame {

    private static InfDB idb;
    private String password;
    private boolean ottoSelected;
    private boolean judithSelected;
    private boolean barnBarnSelected;
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseUser = new javax.swing.JLabel();
        tglBtnJudith = new javax.swing.JToggleButton();
        tglBtnOtto = new javax.swing.JToggleButton();
        tglBtnBarnBarn = new javax.swing.JToggleButton();
        pwField = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChooseUser.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblChooseUser.setText("Välj användare");

        tglBtnJudith.setText("Judith");
        tglBtnJudith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnJudithActionPerformed(evt);
            }
        });

        tglBtnOtto.setText("Otto");
        tglBtnOtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnOttoActionPerformed(evt);
            }
        });

        tglBtnBarnBarn.setText("Barnbarn");
        tglBtnBarnBarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnBarnBarnActionPerformed(evt);
            }
        });

        pwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwFieldActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPassword.setText("Ange lösenord");

        btnLogin.setText("Logga in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(tglBtnJudith, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tglBtnOtto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tglBtnBarnBarn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword))
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblChooseUser)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblChooseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglBtnOtto)
                    .addComponent(tglBtnJudith)
                    .addComponent(tglBtnBarnBarn))
                .addGap(30, 30, 30)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglBtnOttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnOttoActionPerformed
        if(tglBtnOtto.isSelected()) {
            ottoSelected = true;
            judithSelected = false;
            barnBarnSelected = false;
            tglBtnJudith.setSelected(false);
            tglBtnBarnBarn.setSelected(false);
        }
    }//GEN-LAST:event_tglBtnOttoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(checkEmpty(pwField)) {
            lblError.setText("Vänligen ange ett lösenord!");
        }
        else {
            try{
                String password = pwField.getText();
                if((!ottoSelected) && (!judithSelected) && (!barnBarnSelected)) {
                    lblError.setText("Vänligen välj användare!");
                }
                if(judithSelected){
                    String sqlQueryJudith = "Select Password from Employee where Name = 'Judith';";
                    String resultJudith = idb.fetchSingle(sqlQueryJudith); 
                    
                    if(password.equals(resultJudith)){
                        new UserPage().setVisible(true);
                        dispose();
                    }
                    else {
                        lblError.setText("Ogiltigt lösenord!");
                    }
                }
                if(ottoSelected){
                    String sqlQueryOtto = "Select Password from Employee where Name = 'Otto' ;" ;
                    String resultOtto = idb.fetchSingle(sqlQueryOtto);
                    
                    if(password.equals(resultOtto)){
                        new UserPage().setVisible(true);
                        dispose();
                    }
                    else {
                        lblError.setText("Ogiltigt lösenord!");
                    }
                }
                if(barnBarnSelected){
                    String sqlQueryBarnBarn = "Select Password from Employee where Name = 'Barnbarn' ;" ;
                    String resultBarnBarn = idb.fetchSingle(sqlQueryBarnBarn);
                    
                    if(password.equals(resultBarnBarn)){
                        new UserPage().setVisible(true);
                        dispose();
                    }
                    else {
                        lblError.setText("Ogiltigt lösenord!");
                    }
                }
            }
            catch(InfException e) {
                JOptionPane.showMessageDialog(null, "Databasfel");
                System.out.println("Databasfel " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tglBtnJudithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnJudithActionPerformed
        if(tglBtnJudith.isSelected()) {
            judithSelected = true;
            ottoSelected = false;
            barnBarnSelected = false;
            tglBtnOtto.setSelected(false);
            tglBtnBarnBarn.setSelected(false);
        }
    }//GEN-LAST:event_tglBtnJudithActionPerformed

    private void tglBtnBarnBarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnBarnBarnActionPerformed
        if(tglBtnBarnBarn.isSelected()) {
            barnBarnSelected = true;
            judithSelected = false;
            ottoSelected = false;
            tglBtnJudith.setSelected(false);
            tglBtnBarnBarn.setSelected(false);
        }
    }//GEN-LAST:event_tglBtnBarnBarnActionPerformed

    private void pwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwFieldActionPerformed
        
    }//GEN-LAST:event_pwFieldActionPerformed

    public boolean checkEmpty(JPasswordField aPwField) {
        boolean isEmpty = false;
        if(aPwField.getText().isEmpty()) {
            isEmpty = true;
        }
        return isEmpty;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblChooseUser;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JToggleButton tglBtnBarnBarn;
    private javax.swing.JToggleButton tglBtnJudith;
    private javax.swing.JToggleButton tglBtnOtto;
    // End of variables declaration//GEN-END:variables
}
