/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;

import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.ImageIcon;

/**
 *
 * @author tommy
 */
public class openFraktsedel extends javax.swing.JFrame {

    private InfDB idb;
    private String selectedOrderID;
    ImageIcon imageBarCode = new ImageIcon("BarCode1.png");
  
    /**
     * Creates new form openFraktsedel
     * 
     * @param idb
     * @param selectedOrderID
     */
    public openFraktsedel(InfDB idb,String selectedOrderID) {
        initComponents();
        this.idb= idb;
        this.selectedOrderID = selectedOrderID;
        fillIDLabel();
        fetchCustomerID();
        fetchCustomerName();
        fetchCustomerStreet();
        fetchCustomerHouseNumber();
        fetchShippingDate();
        this.setLocationRelativeTo(null);
        lblBarCode.setIcon(imageBarCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoBack = new javax.swing.JButton();
        lblHeadline1 = new javax.swing.JLabel();
        lblHeadline2 = new javax.swing.JLabel();
        lblHeadline8 = new javax.swing.JLabel();
        lblHeadline9 = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblHeadline3 = new javax.swing.JLabel();
        lblHeadline4 = new javax.swing.JLabel();
        lblHeadline5 = new javax.swing.JLabel();
        lblHeadline11 = new javax.swing.JLabel();
        lblHeadline10 = new javax.swing.JLabel();
        lblHeadline6 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerAdress = new javax.swing.JLabel();
        lblCustomerHouseNumber = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lblHeadline7 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblBarCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGoBack.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnGoBack.setText("Tillbaka");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblHeadline1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblHeadline1.setText("Fraktsedel Paket");

        lblHeadline2.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblHeadline2.setText("From:");

        lblHeadline8.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblHeadline8.setText("CustNO:");

        lblHeadline9.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblHeadline9.setText("OrdNO:");

        lblOrderID.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblCustomerID.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblHeadline3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblHeadline3.setText("Ottos och Jutiths hattar");

        lblHeadline4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblHeadline4.setText("Tyrolerhattsvägen 5");

        lblHeadline5.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblHeadline5.setText("123 45 Hattvik");

        lblHeadline11.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblHeadline11.setText("012-345 678");

        lblHeadline10.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lblHeadline10.setText("Phone:");

        lblHeadline6.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblHeadline6.setText("To:");

        lblCustomerName.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblCustomerAdress.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblCustomerHouseNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        sep1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        lblHeadline7.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblHeadline7.setText("Date:");

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblHeadline1)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(sep1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeadline2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeadline8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeadline3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeadline9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeadline4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeadline5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeadline10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHeadline11)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHeadline6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCustomerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCustomerHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblHeadline7)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(lblBarCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeadline1)
                .addGap(2, 2, 2)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeadline2)
                        .addComponent(lblHeadline8))
                    .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadline9)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeadline3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeadline4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeadline5)
                    .addComponent(lblHeadline11)
                    .addComponent(lblHeadline10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeadline6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCustomerHouseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                    .addComponent(lblCustomerAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeadline7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void fillIDLabel(){
        lblOrderID.setText(selectedOrderID);
    }
    
    private void fetchCustomerID(){
        try{
            String query = "SELECT Customer from `Order` where OrderID = '" + lblOrderID.getText() + "'";
            String result = idb.fetchSingle(query);
            lblCustomerID.setText(result);
        } catch (InfException ex) {
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void fetchCustomerName(){
        try{
            String query = "SELECT Name from Customer join `Order` O on Customer.CustomerID = O.Customer where OrderID = '" + lblOrderID.getText() + "'";
            String result = idb.fetchSingle(query);
            lblCustomerName.setText(result);
        } catch (InfException ex) {
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void fetchCustomerStreet(){
        try{
            String query = "SELECT Street from Address join `Order` O on Address.Customer = O.Customer where OrderID = '" + lblOrderID.getText() + "'";
            String result = idb.fetchSingle(query);
            lblCustomerAdress.setText(result);
        } catch (InfException ex) {
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void fetchCustomerHouseNumber(){
        try{
            String query = "SELECT House_number from Address join `Order` O on Address.Customer = O.Customer where OrderID = '" + lblOrderID.getText() + "'";
            String result = idb.fetchSingle(query);
            lblCustomerHouseNumber.setText(result);
        } catch (InfException ex) {
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void fetchShippingDate(){
        try{
            String query = "Select Shipment_date from `Order` where OrderID = '"+ lblOrderID.getText()+ "'";
            String result = idb.fetchSingle(query);
            lblDate.setText(result);
        } catch (InfException ex){
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JLabel lblBarCode;
    private javax.swing.JLabel lblCustomerAdress;
    private javax.swing.JLabel lblCustomerHouseNumber;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHeadline1;
    private javax.swing.JLabel lblHeadline10;
    private javax.swing.JLabel lblHeadline11;
    private javax.swing.JLabel lblHeadline2;
    private javax.swing.JLabel lblHeadline3;
    private javax.swing.JLabel lblHeadline4;
    private javax.swing.JLabel lblHeadline5;
    private javax.swing.JLabel lblHeadline6;
    private javax.swing.JLabel lblHeadline7;
    private javax.swing.JLabel lblHeadline8;
    private javax.swing.JLabel lblHeadline9;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JSeparator sep1;
    // End of variables declaration//GEN-END:variables
}
