/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author buggi
 */
public class openTullsedel extends javax.swing.JFrame {

    private InfDB idb;
    private String selectedOrderID;

    /**
     * Creates new form openTullsedel
     * @param idb
     * @param selectedOrderID
     *
     */
    public openTullsedel(InfDB idb, String selectedOrderID) {
        initComponents();
        this.idb = idb;
        this.selectedOrderID = selectedOrderID;
        GenerateRandom();
        fetchShippingDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainHeadline = new javax.swing.JLabel();
        lblPostNord = new javax.swing.JLabel();
        lblCdId = new javax.swing.JLabel();
        lblDeclarationNumber = new javax.swing.JLabel();
        lblInstructionSwedish = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInstructionEnglish = new javax.swing.JLabel();
        lblGift = new javax.swing.JLabel();
        lblDocument = new javax.swing.JLabel();
        lblSaleGoods = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        lblShipmentDate = new javax.swing.JLabel();
        lblDateHeadline = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGoBack = new javax.swing.JButton();
        txtfldGift = new javax.swing.JTextField();
        txtfldDocument = new javax.swing.JTextField();
        txtfldSaleGoods = new javax.swing.JTextField();
        txtfldOther = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainHeadline.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMainHeadline.setText("CUSTOMS DECLARATION");

        lblPostNord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPostNord.setText("PostNord");

        lblCdId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCdId.setText("CD");

        lblDeclarationNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblInstructionSwedish.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblInstructionSwedish.setText("Får öppnas av myndigheter");

        lblInstructionEnglish.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblInstructionEnglish.setText("May be opened officially");

        lblGift.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblGift.setText("Gåva/Gift");

        lblDocument.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDocument.setText("Dokument/Document");

        lblSaleGoods.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblSaleGoods.setText("Sålda varor/Sale of goods");

        lblOther.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblOther.setText("Annat/Other");

        lblShipmentDate.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        lblDateHeadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDateHeadline.setText("Date:");

        btnGoBack.setText("Tillbaka");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        txtfldGift.setEditable(false);
        txtfldGift.setBackground(new java.awt.Color(255, 255, 255));
        txtfldGift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldGiftActionPerformed(evt);
            }
        });

        txtfldDocument.setEditable(false);
        txtfldDocument.setBackground(new java.awt.Color(255, 255, 255));

        txtfldSaleGoods.setEditable(false);
        txtfldSaleGoods.setBackground(new java.awt.Color(255, 255, 255));

        txtfldOther.setEditable(false);
        txtfldOther.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPostNord)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInstructionSwedish)
                                            .addComponent(lblInstructionEnglish))
                                        .addGap(23, 23, 23)
                                        .addComponent(lblCdId))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtfldSaleGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(lblSaleGoods)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfldOther, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOther)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDeclarationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMainHeadline)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtfldGift, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblGift)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfldDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDocument)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDateHeadline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShipmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoBack))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDateHeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipmentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoBack)))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainHeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeclarationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPostNord)
                        .addComponent(lblCdId))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInstructionSwedish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstructionEnglish)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGift)
                    .addComponent(txtfldGift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocument))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleGoods)
                    .addComponent(txtfldSaleGoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void fetchShippingDate(){
        try{
            String query = "Select Shipment_date from `Order` where OrderID = '"+ selectedOrderID+ "'";
            String result = idb.fetchSingle(query);
            lblShipmentDate.setText(result);
        } catch (InfException ex){
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void txtfldGiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldGiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldGiftActionPerformed

    private void GenerateRandom(){
        Random number = new Random();
        int lowerbound = 10;
        int upperbound = 99;
        int genRan = number.nextInt(lowerbound, upperbound);
        lblDeclarationNumber.setText(Integer.toString(genRan));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCdId;
    private javax.swing.JLabel lblDateHeadline;
    private javax.swing.JLabel lblDeclarationNumber;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblGift;
    private javax.swing.JLabel lblInstructionEnglish;
    private javax.swing.JLabel lblInstructionSwedish;
    private javax.swing.JLabel lblMainHeadline;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblPostNord;
    private javax.swing.JLabel lblSaleGoods;
    private javax.swing.JLabel lblShipmentDate;
    private javax.swing.JTextField txtfldDocument;
    private javax.swing.JTextField txtfldGift;
    private javax.swing.JTextField txtfldOther;
    private javax.swing.JTextField txtfldSaleGoods;
    // End of variables declaration//GEN-END:variables
}
