/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author buggi
 */
public class openTullsedel extends javax.swing.JFrame {

    private InfDB idb;
    private String selectedOrderID;

    /**
     * Creates new form openTullsedel
     * @param idb
     * @param selectedOrderID
     *
     */
    public openTullsedel(InfDB idb, String selectedOrderID) {
        initComponents();
        this.idb = idb;
        this.selectedOrderID = selectedOrderID;
        GenerateRandom();
        fetchShippingDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainHeadline = new javax.swing.JLabel();
        lblPostNord = new javax.swing.JLabel();
        lblCdId = new javax.swing.JLabel();
        lblDeclarationNumber = new javax.swing.JLabel();
        lblInstructionSwedish = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInstructionEnglish = new javax.swing.JLabel();
        txtaeGift = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblGift = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaeDocument = new javax.swing.JTextArea();
        lblDocument = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaeSaleGoods = new javax.swing.JTextArea();
        lblSaleGoods = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaeOther = new javax.swing.JTextArea();
        lblOther = new javax.swing.JLabel();
        lblShipmentDate = new javax.swing.JLabel();
        lblDateHeadline = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGoBack = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainHeadline.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMainHeadline.setText("CUSTOMS DECLARATION");

        lblPostNord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPostNord.setText("PostNord");

        lblCdId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCdId.setText("CD");

        lblDeclarationNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblInstructionSwedish.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblInstructionSwedish.setText("Får öppnas av myndigheter");

        lblInstructionEnglish.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblInstructionEnglish.setText("May be opened officially");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtaeGift.setViewportView(jTextArea1);

        lblGift.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblGift.setText("Gåva/Gift");

        txtaeDocument.setEditable(false);
        txtaeDocument.setColumns(20);
        txtaeDocument.setRows(5);
        jScrollPane1.setViewportView(txtaeDocument);

        lblDocument.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDocument.setText("Dokument/Document");

        txtaeSaleGoods.setEditable(false);
        txtaeSaleGoods.setColumns(20);
        txtaeSaleGoods.setRows(5);
        jScrollPane2.setViewportView(txtaeSaleGoods);

        lblSaleGoods.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblSaleGoods.setText("Sålda varor/Sale of goods");

        txtaeOther.setEditable(false);
        txtaeOther.setColumns(20);
        txtaeOther.setRows(5);
        jScrollPane3.setViewportView(txtaeOther);

        lblOther.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblOther.setText("Annat/Other");

        lblShipmentDate.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        lblDateHeadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDateHeadline.setText("Date:");

        btnGoBack.setText("Tillbaka");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPostNord)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInstructionSwedish)
                                            .addComponent(lblInstructionEnglish))
                                        .addGap(23, 23, 23)
                                        .addComponent(lblCdId))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSaleGoods)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOther)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDeclarationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMainHeadline)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtaeGift, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblGift)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDocument)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDateHeadline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShipmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoBack))
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDateHeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipmentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoBack)))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainHeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPostNord)
                        .addComponent(lblCdId)
                        .addComponent(lblDeclarationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInstructionSwedish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstructionEnglish)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtaeGift, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGift))
                                    .addGap(3, 3, 3))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDocument))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaleGoods)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void fetchShippingDate(){
        try{
            String query = "Select Shipment_date from `Order` where OrderID = '"+ selectedOrderID+ "'";
            String result = idb.fetchSingle(query);
            lblShipmentDate.setText(result);
        } catch (InfException ex){
            Logger.getLogger(showOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void GenerateRandom(){
        Random number = new Random();
        int lowerbound = 10;
        int upperbound = 99;
        int genRan = number.nextInt(lowerbound, upperbound);
        lblDeclarationNumber.setText(Integer.toString(genRan));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCdId;
    private javax.swing.JLabel lblDateHeadline;
    private javax.swing.JLabel lblDeclarationNumber;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblGift;
    private javax.swing.JLabel lblInstructionEnglish;
    private javax.swing.JLabel lblInstructionSwedish;
    private javax.swing.JLabel lblMainHeadline;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblPostNord;
    private javax.swing.JLabel lblSaleGoods;
    private javax.swing.JLabel lblShipmentDate;
    private javax.swing.JTextArea txtaeDocument;
    private javax.swing.JScrollPane txtaeGift;
    private javax.swing.JTextArea txtaeOther;
    private javax.swing.JTextArea txtaeSaleGoods;
    // End of variables declaration//GEN-END:variables
}
