/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author buggi
 */
public class showWorkload extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form showWorkload
     * @param idb
     */
    public showWorkload(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainHeadline = new javax.swing.JLabel();
        lblChooseEmployeeHeadline = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaeShowOrder = new javax.swing.JTextArea();
        cmbChooseEmployee = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainHeadline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMainHeadline.setText("Visa arbetsbelastning");

        lblChooseEmployeeHeadline.setText("Välj vilken hattmakares arbetsbelastningen som ska visas");

        txtaeShowOrder.setColumns(20);
        txtaeShowOrder.setRows(5);
        jScrollPane1.setViewportView(txtaeShowOrder);

        cmbChooseEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Otto", "Judith", "Barnbarn" }));
        cmbChooseEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChooseEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMainHeadline)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblChooseEmployeeHeadline)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbChooseEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblMainHeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChooseEmployeeHeadline)
                .addGap(12, 12, 12)
                .addComponent(cmbChooseEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cmbChooseEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChooseEmployeeActionPerformed
        // TODO add your handling code here:
        txtaeShowOrder.setText("");
        ArrayList<HashMap<String, String>> searchedOrders;
        String chosenEmployee = cmbChooseEmployee.getSelectedItem().toString();
        try{
            if(chosenEmployee.equals("Judith")){
                String queryJudith = "SELECT `order`.OrderID, customer.Name, o.Order_date\n" +
                "FROM `order`, customer\n" +
                "JOIN `order` o on customer.CustomerID = o.Customer\n" +
                "JOIN employee e on e.EmployeeID = o.Created_by_employee\n" +
                "WHERE EmployeeID = '1'";
                searchedOrders = idb.fetchRows(queryJudith);
                
                for (HashMap<String, String> oneOrder:searchedOrders){
                    txtaeShowOrder.setText(oneOrder.get("OrderID" + "Name"));
                }
            }
            
        }
        catch (InfException ex) {
               Logger.getLogger(searchInvoice.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_cmbChooseEmployeeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbChooseEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChooseEmployeeHeadline;
    private javax.swing.JLabel lblMainHeadline;
    private javax.swing.JTextArea txtaeShowOrder;
    // End of variables declaration//GEN-END:variables
}
