/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakare_projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author theosohlman
 */
public class UserPage extends javax.swing.JFrame {
    private static InfDB idb;
    private int employeeIdet;
    

    /**
     * Creates new form UserPage
     */
    public UserPage(InfDB idb,int employeeId) {
        initComponents();
        this.idb = idb;
        this.employeeIdet = employeeId;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblHeaderSecond = new javax.swing.JLabel();
        btnRegisterCustomer = new javax.swing.JButton();
        btnRegisterOrder = new javax.swing.JButton();
        btnShowOrderInfo = new javax.swing.JButton();
        btnShowCustomerInfo = new javax.swing.JButton();
        btnChangeInfoCustomer = new javax.swing.JButton();
        btnChangeOrderStatus = new javax.swing.JButton();
        btnShowStatistics = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnCreateInvoice = new javax.swing.JButton();
        btnChangeOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblHeader.setText("Välkommen");

        lblHeaderSecond.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblHeaderSecond.setText("Vad vill du göra?");

        btnRegisterCustomer.setText("Registera ny kund");
        btnRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCustomerActionPerformed(evt);
            }
        });

        btnRegisterOrder.setText("Registrera förfrågan");
        btnRegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterOrderActionPerformed(evt);
            }
        });

        btnShowOrderInfo.setText("Visa order");
        btnShowOrderInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowOrderInfoActionPerformed(evt);
            }
        });

        btnShowCustomerInfo.setText("Se information om kund");
        btnShowCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCustomerInfoActionPerformed(evt);
            }
        });

        btnChangeInfoCustomer.setText("Ändra information om kund");
        btnChangeInfoCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoCustomerActionPerformed(evt);
            }
        });

        btnChangeOrderStatus.setText("Ändra status på order");

        btnShowStatistics.setText("Se statistik");

        btnPrint.setText("Skriv ut frakt och tullsedel");

        btnCreateInvoice.setText("Skapa faktura");
        btnCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInvoiceActionPerformed(evt);
            }
        });

        btnChangeOrder.setText("Ändra i order");
        btnChangeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeaderSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegisterCustomer)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegisterOrder)
                                    .addComponent(btnChangeOrderStatus)
                                    .addComponent(btnChangeOrder))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPrint)
                                    .addComponent(btnCreateInvoice)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowCustomerInfo)
                                    .addComponent(btnChangeInfoCustomer))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowOrderInfo)
                                    .addComponent(btnShowStatistics)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblHeader)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(lblHeaderSecond)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterCustomer)
                    .addComponent(btnShowOrderInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowCustomerInfo)
                    .addComponent(btnShowStatistics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeInfoCustomer)
                .addGap(67, 67, 67)
                .addComponent(btnRegisterOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateInvoice)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChangeOrder)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnChangeOrderStatus))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCustomerActionPerformed
        new RegistreraKund(idb).setVisible(true);
    }//GEN-LAST:event_btnRegisterCustomerActionPerformed

    private void btnRegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterOrderActionPerformed
      new RegisterOrder(idb,employeeIdet).setVisible(true);
     
    }//GEN-LAST:event_btnRegisterOrderActionPerformed

    private void btnShowOrderInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowOrderInfoActionPerformed
        // TODO add your handling code here:
        new searchOrder(idb, employeeIdet).setVisible(true);
    }//GEN-LAST:event_btnShowOrderInfoActionPerformed

    private void btnShowCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCustomerInfoActionPerformed
        new showCustomerInfo(idb).setVisible(true);
    }//GEN-LAST:event_btnShowCustomerInfoActionPerformed

    private void btnCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInvoiceActionPerformed
        // TODO add your handling code here:
        new searchInvoice(idb, employeeIdet).setVisible(true);
    }//GEN-LAST:event_btnCreateInvoiceActionPerformed

    private void btnChangeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeOrderActionPerformed
        // TODO add your handling code here:
        new ChooseCustomerAndOrder(idb).setVisible(true);
    }//GEN-LAST:event_btnChangeOrderActionPerformed

    private void btnChangeInfoCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoCustomerActionPerformed
        new ChangeCustomerInfo(idb).setVisible(true);
    }//GEN-LAST:event_btnChangeInfoCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeInfoCustomer;
    private javax.swing.JButton btnChangeOrder;
    private javax.swing.JButton btnChangeOrderStatus;
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRegisterCustomer;
    private javax.swing.JButton btnRegisterOrder;
    private javax.swing.JButton btnShowCustomerInfo;
    private javax.swing.JButton btnShowOrderInfo;
    private javax.swing.JButton btnShowStatistics;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeaderSecond;
    // End of variables declaration//GEN-END:variables
}
